
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

features:
  - buildpack-stack=ubuntu-22

name: peace-prod-tor
region: tor

ingress:
  rules:
  - component:
      name: peace-prod-tor
      preserve_path_prefix: true
    match:
      path:
        prefix: /

services:
  - dockerfile_path: /Dockerfile
    envs:
    - key: PEACE_MONGODB_URIS
      scope: RUN_TIME
      value: ${db-mongodb-tor1-94843.DATABASE_URL}
      type: SECRET
    - key: MONGODB_CA_CERT
      scope: RUN_TIME
      value: ${db-mongodb-tor1-94843.CA_CERT}
      type: SECRET
    http_port: 3000
    image:
      deploy_on_push:
        enabled: true
      registry: ghcr.io
      registry_type: GHCR
      repository: lilyanavalley/peace
      tag: latest
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-2gb
    name: peace-prod-tor
    source_dir: /

databases:
  - cluster_name: db-mongodb-tor1-94843
    engine: MONGODB
    name: db-mongodb-tor1-94843
    production: true
    version: "7"
