
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

features:
  - buildpack-stack=ubuntu-22

name: peace-web
region: tor

ingress:
  rules:
    - match:
        path:
          prefix: /
      component:
        name: leptos-ssr

services:
  - name: leptos-ssr
    image:
      registry_type: GHCR
      registry: ghcr.io
      repository: lilyanavalley/peace
      tag: latest
      deploy_on_push:
        enabled: true
    instance_count: 1
    instance_size_slug: basic-xxs
    # http_port: 8080

databases:
  - name: mongodb
    engine: MONGODB
    version: "7"
    production: false
